# Generated by Django 4.1.5 on 2023-08-29 08:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='referral_code',
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True),
        ),
    ]
